# Generated by Django 5.1.2 on 2024-10-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='url',
            field=models.TextField(verbose_name='URL'),
        ),
    ]
