# Generated by Django 5.0.6 on 2024-06-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Окошко')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
            ],
            options={
                'verbose_name': 'Окошко',
                'verbose_name_plural': 'Окошки',
            },
        ),
    ]
