# Generated by Django 5.0.6 on 2024-07-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_window_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='window',
            name='approved',
        ),
    ]
