# Generated by Django 5.0.6 on 2024-07-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pricelist_works'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricelist',
        ),
    ]
