# Generated by Django 5.0.6 on 2024-07-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='name',
        ),
    ]
