# Generated by Django 5.0.6 on 2024-07-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_window_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
